// <auto-generated />
using System;
using FitnessCalculationEngine.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCalculationEngine.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260628220613_AddStatusLookup")]
    partial class AddStatusLookup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCalculationEngine.Entities.CalculatedMetrics", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<double>("BMR")
                        .HasColumnType("float");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("TDEE")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CalculatedMetrics");
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.FitnessPlanConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<double>("CalorieMax")
                        .HasColumnType("float");

                    b.Property<double>("CalorieMin")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalPlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FitnessPlanConfigs");
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.Lookup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Name = "Male",
                            Value = 1.0
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Name = "Female",
                            Value = 2.0
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2L,
                            Name = "Rookie",
                            Value = 1.2
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2L,
                            Name = "Beginner",
                            Value = 1.375
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 2L,
                            Name = "Intermediate",
                            Value = 1.55
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 2L,
                            Name = "Advance",
                            Value = 1.7250000000000001
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 2L,
                            Name = "TrueBeast",
                            Value = 1.8999999999999999
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 3L,
                            Name = "Lose Weight",
                            Value = -500.0
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 3L,
                            Name = "Gain Weight",
                            Value = 300.0
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 3L,
                            Name = "Gain More Flexible",
                            Value = 150.0
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 3L,
                            Name = "Get Fitter/Learn the Basic",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 4L,
                            Name = "Weak",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 4L,
                            Name = "Normal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 4L,
                            Name = "Hard",
                            Value = 0.0
                        });
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.LookupCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LookupCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Gender"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "ActivityLevel"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Goal"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Status"
                        });
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.UserAssignedPlan", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalPlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserAssignedPlans");
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.UserFitnessStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityLevelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<long>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex("GenderId");

                    b.HasIndex("GoalId");

                    b.ToTable("UserFitnessStats");
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.UserPlanHistory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalPlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonForChange")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserPlanHistories");
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.Lookup", b =>
                {
                    b.HasOne("FitnessCalculationEngine.Entities.LookupCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FitnessCalculationEngine.Entities.UserFitnessStats", b =>
                {
                    b.HasOne("FitnessCalculationEngine.Entities.Lookup", "ActivityLevel")
                        .WithMany()
                        .HasForeignKey("ActivityLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessCalculationEngine.Entities.Lookup", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessCalculationEngine.Entities.Lookup", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityLevel");

                    b.Navigation("Gender");

                    b.Navigation("Goal");
                });
#pragma warning restore 612, 618
        }
    }
}
