using FitnessCalculationEngine.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FitnessCalculationEngine.Data.ModelConfiguration
{
    public class UserAssignedPlanConfiguration : IEntityTypeConfiguration<UserAssignedPlan>
    {
        public void Configure(EntityTypeBuilder<UserAssignedPlan> builder)
        {
            builder.HasKey(x => x.Id);

            // Primary Key must match Users.Id from Auth database, so it shouldn't be auto-generated by the DB
            builder.Property(x => x.Id).ValueGeneratedNever();

            builder.Property(x => x.ExternalPlanId).HasMaxLength(50);
        }
    }
}
